#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inventario(object):
    def setupUi(self, inventario):
        inventario.setObjectName("inventario")
        inventario.resize(770, 450)
        inventario.setStyleSheet("background-color: rgb(38, 0, 28);")
        self.centralwidget = QtWidgets.QWidget(inventario)
        self.centralwidget.setObjectName("centralwidget")
        self.inv_label_producto = QtWidgets.QLabel(self.centralwidget)
        self.inv_label_producto.setGeometry(QtCore.QRect(20, 90, 71, 31))
        self.inv_label_producto.setStyleSheet("color: rgb(255, 255, 255);")
        self.inv_label_producto.setObjectName("inv_label_producto")
        self.inv_label_cantidad = QtWidgets.QLabel(self.centralwidget)
        self.inv_label_cantidad.setGeometry(QtCore.QRect(390, 90, 71, 31))
        self.inv_label_cantidad.setStyleSheet("color: rgb(255, 255, 255);")
        self.inv_label_cantidad.setObjectName("inv_label_cantidad")
        self.inv_label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.inv_label_titulo.setGeometry(QtCore.QRect(40, 10, 671, 51))
        self.inv_label_titulo.setStyleSheet("")
        self.inv_label_titulo.setObjectName("inv_label_titulo")
        self.inv_label_lista_inventario = QtWidgets.QLabel(self.centralwidget)
        self.inv_label_lista_inventario.setGeometry(QtCore.QRect(20, 210, 181, 21))
        self.inv_label_lista_inventario.setStyleSheet("color: rgb(255, 255, 255);")
        self.inv_label_lista_inventario.setObjectName("inv_label_lista_inventario")
        self.inv_button_newProducto = QtWidgets.QPushButton(self.centralwidget)
        self.inv_button_newProducto.setGeometry(QtCore.QRect(590, 150, 141, 31))
        self.inv_button_newProducto.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.inv_button_newProducto.setObjectName("inv_button_newProducto")
        self.inv_button_newProveedor = QtWidgets.QPushButton(self.centralwidget)
        self.inv_button_newProveedor.setGeometry(QtCore.QRect(410, 150, 141, 31))
        self.inv_button_newProveedor.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.inv_button_newProveedor.setObjectName("inv_button_newProveedor")
        self.inv_text_cantidad = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inv_text_cantidad.setGeometry(QtCore.QRect(470, 90, 271, 31))
        self.inv_text_cantidad.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.inv_text_cantidad.setObjectName("inv_text_cantidad")
        self.inv_label_proveedor = QtWidgets.QLabel(self.centralwidget)
        self.inv_label_proveedor.setGeometry(QtCore.QRect(20, 150, 71, 31))
        self.inv_label_proveedor.setStyleSheet("color: rgb(255, 255, 255);")
        self.inv_label_proveedor.setObjectName("inv_label_proveedor")
        self.inv_box_proveedorStock = QtWidgets.QComboBox(self.centralwidget)
        self.inv_box_proveedorStock.setGeometry(QtCore.QRect(100, 150, 271, 31))
        self.inv_box_proveedorStock.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.inv_box_proveedorStock.setObjectName("inv_box_proveedorStock")
        self.inv_listView_inventario = QtWidgets.QListView(self.centralwidget)
        self.inv_listView_inventario.setGeometry(QtCore.QRect(20, 250, 731, 111))
        self.inv_listView_inventario.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.inv_listView_inventario.setObjectName("inv_listView_inventario")
        self.inv_button_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.inv_button_regresar.setGeometry(QtCore.QRect(600, 370, 141, 31))
        self.inv_button_regresar.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.inv_button_regresar.setObjectName("inv_button_regresar")
        self.inv_box_productoStock = QtWidgets.QComboBox(self.centralwidget)
        self.inv_box_productoStock.setGeometry(QtCore.QRect(100, 90, 271, 31))
        self.inv_box_productoStock.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.inv_box_productoStock.setObjectName("inv_box_productoStock")
        # inventario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inventario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName("menubar")
        # inventario.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inventario)
        self.statusbar.setObjectName("statusbar")
        # inventario.setStatusBar(self.statusbar)

        self.retranslateUi(inventario)
        QtCore.QMetaObject.connectSlotsByName(inventario)

        # Se define las funciones cuandos se oprime un boton.
        self.inv_button_newProducto.clicked.connect(self.nuevo_producto)
        self.inv_button_newProveedor.clicked.connect(self.nuevo_proveedor)
        self.inv_button_addProducto.clicked.connect(self.agregar_producto)
        self.inv_button_regresar.clicked.connect(self.regresar)

    def retranslateUi(self, inventario):
        _translate = QtCore.QCoreApplication.translate
        inventario.setWindowTitle(_translate("inventario", "MainWindow"))
        self.inv_label_producto.setText(_translate("inventario", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Producto:</span></p></body></html>"))
        self.inv_label_cantidad.setText(_translate("inventario", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Cantidad:</span></p></body></html>"))
        self.inv_label_titulo.setText(_translate("inventario", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00b6b6;\">INVENTARIO</span></p></body></html>"))
        self.inv_label_lista_inventario.setText(_translate("inventario", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">Productos en inventario:</span></p></body></html>"))
        self.inv_button_newProducto.setText(_translate("inventario", "Nuevo producto"))
        self.inv_button_newProveedor.setText(_translate("inventario", "Nuevo Proveedor"))
        self.inv_label_proveedor.setText(_translate("inventario", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Proveedor:</span></p></body></html>"))
        self.inv_button_regresar.setText(_translate("inventario", "Regresar"))

    def agregar_producto(self):
        self.Funciones_DB.agregar_producto_proveedor(
            [
            str(self.inv_box_productoStock.toPlainText()),
            str(self.inv_box_proveedorStock.toPlainText()),
            str(self.inv_text_cantidad.toPlainText())
            ]
        )

    def nuevo_proveedor(self):
        self.Funciones_DB.ingresar_proveedor(

        )



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Data = QtWidgets.QDialog()
    ui = Ui_inventario()
    ui.setupUi(Data)
    Data.show()
    sys.exit(app.exec_())
