#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventarioSub_provedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inv2_provedor(object):
    def setupUi(self, inv2_provedor):
        inv2_provedor.setObjectName("inv2_provedor")
        inv2_provedor.resize(402, 189)
        inv2_provedor.setStyleSheet("background-color: rgb(38, 0, 28);")
        self.centralwidget = QtWidgets.QWidget(inv2_provedor)
        self.centralwidget.setObjectName("centralwidget")
        self.proveedor_label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.proveedor_label_titulo.setGeometry(QtCore.QRect(30, 0, 351, 51))
        self.proveedor_label_titulo.setStyleSheet("")
        self.proveedor_label_titulo.setObjectName("proveedor_label_titulo")
        self.proveedor_button_newProveedor = QtWidgets.QPushButton(self.centralwidget)
        self.proveedor_button_newProveedor.setGeometry(QtCore.QRect(210, 110, 151, 31))
        self.proveedor_button_newProveedor.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.proveedor_button_newProveedor.setObjectName("proveedor_button_newProveedor")
        self.proveedor_label_newProveedor = QtWidgets.QLabel(self.centralwidget)
        self.proveedor_label_newProveedor.setGeometry(QtCore.QRect(20, 70, 121, 31))
        self.proveedor_label_newProveedor.setStyleSheet("color: rgb(255, 255, 255);")
        self.proveedor_label_newProveedor.setObjectName("proveedor_label_newProveedor")
        self.proveedor_text_newProveedor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.proveedor_text_newProveedor.setGeometry(QtCore.QRect(150, 70, 241, 31))
        self.proveedor_text_newProveedor.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.proveedor_text_newProveedor.setObjectName("proveedor_text_newProveedor")
        self.proveedor_button_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.proveedor_button_regresar.setGeometry(QtCore.QRect(30, 110, 141, 31))
        self.proveedor_button_regresar.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.proveedor_button_regresar.setObjectName("proveedor_button_regresar")
        inv2_provedor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inv2_provedor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        inv2_provedor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inv2_provedor)
        self.statusbar.setObjectName("statusbar")
        inv2_provedor.setStatusBar(self.statusbar)

        self.retranslateUi(inv2_provedor)
        QtCore.QMetaObject.connectSlotsByName(inv2_provedor)

    def retranslateUi(self, inv2_provedor):
        _translate = QtCore.QCoreApplication.translate
        inv2_provedor.setWindowTitle(_translate("inv2_provedor", "MainWindow"))
        self.proveedor_label_titulo.setText(_translate("inv2_provedor", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00b6b6;\">Añadir nuevo proveedor</span></p></body></html>"))
        self.proveedor_button_newProveedor.setText(_translate("inv2_provedor", "Agregar Nuevo Proveedor"))
        self.proveedor_label_newProveedor.setText(_translate("inv2_provedor", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Nuevo Proveedor:</span></p></body></html>"))
        self.proveedor_button_regresar.setText(_translate("inv2_provedor", "Regresar"))
