# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventarioSub_variosProductos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inv2_variosProductos(object):
    def setupUi(self, inv2_variosProductos):
        inv2_variosProductos.setObjectName("inv2_variosProductos")
        inv2_variosProductos.resize(416, 253)
        inv2_variosProductos.setStyleSheet("background-color: rgb(38, 0, 28);")
        self.centralwidget = QtWidgets.QWidget(inv2_variosProductos)
        self.centralwidget.setObjectName("centralwidget")
        self.varProd_label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.varProd_label_titulo.setGeometry(QtCore.QRect(30, 0, 351, 51))
        self.varProd_label_titulo.setStyleSheet("")
        self.varProd_label_titulo.setObjectName("varProd_label_titulo")
        self.varProd_button_newProducto = QtWidgets.QPushButton(self.centralwidget)
        self.varProd_button_newProducto.setGeometry(QtCore.QRect(220, 170, 151, 31))
        self.varProd_button_newProducto.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.varProd_button_newProducto.setObjectName("varProd_button_newProducto")
        self.varProd_label_producto = QtWidgets.QLabel(self.centralwidget)
        self.varProd_label_producto.setGeometry(QtCore.QRect(20, 70, 121, 31))
        self.varProd_label_producto.setStyleSheet("color: rgb(255, 255, 255);")
        self.varProd_label_producto.setObjectName("varProd_label_producto")
        self.varProd_text_producto = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.varProd_text_producto.setGeometry(QtCore.QRect(150, 70, 251, 31))
        self.varProd_text_producto.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.varProd_text_producto.setObjectName("varProd_text_producto")
        self.varProd_button_regresar = QtWidgets.QPushButton(self.centralwidget)
        self.varProd_button_regresar.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.varProd_button_regresar.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.varProd_button_regresar.setObjectName("varProd_button_regresar")
        self.varProd_text_precio = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.varProd_text_precio.setGeometry(QtCore.QRect(150, 120, 251, 31))
        self.varProd_text_precio.setStyleSheet("background-color: rgb(124, 124, 124);")
        self.varProd_text_precio.setObjectName("varProd_text_precio")
        self.varProd_label_precio = QtWidgets.QLabel(self.centralwidget)
        self.varProd_label_precio.setGeometry(QtCore.QRect(20, 120, 121, 31))
        self.varProd_label_precio.setStyleSheet("color: rgb(255, 255, 255);")
        self.varProd_label_precio.setObjectName("varProd_label_precio")
        inv2_variosProductos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inv2_variosProductos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        inv2_variosProductos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inv2_variosProductos)
        self.statusbar.setObjectName("statusbar")
        inv2_variosProductos.setStatusBar(self.statusbar)

        self.retranslateUi(inv2_variosProductos)
        QtCore.QMetaObject.connectSlotsByName(inv2_variosProductos)

    def retranslateUi(self, inv2_variosProductos):
        _translate = QtCore.QCoreApplication.translate
        inv2_variosProductos.setWindowTitle(_translate("inv2_variosProductos", "MainWindow"))
        self.varProd_label_titulo.setText(_translate("inv2_variosProductos", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00b6b6;\">Añadir nuevo producto</span></p></body></html>"))
        self.varProd_button_newProducto.setText(_translate("inv2_variosProductos", "Agregar Nuevo Producto"))
        self.varProd_label_producto.setText(_translate("inv2_variosProductos", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Nuevo Producto:</span></p></body></html>"))
        self.varProd_button_regresar.setText(_translate("inv2_variosProductos", "Regresar"))
        self.varProd_label_precio.setText(_translate("inv2_variosProductos", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#ffffff;\">Precio por unidad:</span></p></body></html>"))
